# Setup
title:               Grace Li
tagline:              
description:         
url:                 ligrace.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Grace Li
  url:               ligrace.github.io
  email:             

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
